import Providers from "@/providers/Providers";
import type { Metadata } from "next";

import "swiper/css";
import "swiper/css/navigation";
import "swiper/css/pagination";

import "/public/css/bootstrap.min.css";
import "/public/css/demo.css";
import "/public/css/dropdown-effects/fade-down.css";
import "/public/css/flaticon.css";
import "/public/css/lunar.css";
import "/public/css/menu.css";
// import "/public/css/magnific-popup.css"
// import "/public/css/owl.carousel.min.css"
// import "/public/css/owl.theme.default.min.css"
// import SmoothScroll from "../components/elements/SmoothScroll"
import "/public/css/animate.css";
import "/public/css/pink-theme.css";
import "/public/css/responsive.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
