/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  collections: {
    users: User;
    media: Media;
    pages: Page;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  globals: {};
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  user_name?: string | null;
  roles?: ('admin' | 'user' | 'seller')[] | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  _verified?: boolean | null;
  _verificationToken?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  sizes?: {
    square?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    sixteenByNineMedium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    tablet?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  name: string;
  slug: string;
  layout?:
    | (
        | {
            title: string;
            subtitle: string;
            background_image: string | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero5';
          }
        | {
            caption: string;
            title: string;
            subtitle: string;
            heading: string;
            points: {
              point: string;
              id?: string | null;
            }[];
            background_image: string | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'lnk1_23';
          }
        | {
            caption: string;
            title: string;
            paragraphs: {
              paragraph: string;
              id?: string | null;
            }[];
            background_image: string | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'ct01_28';
          }
        | {
            title: string;
            subtitle: string;
            heading: string;
            paragraph: string;
            points: {
              point: string;
              id?: string | null;
            }[];
            background_image: string | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'ct02_44';
          }
        | {
            caption: string;
            title: string;
            subtitle: string;
            points: {
              point: string;
              id?: string | null;
            }[];
            features: {
              title: string;
              description: string;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'features12_10';
          }
        | {
            statistics: {
              integer: number;
              character: string;
              description: string;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'statistic1_19';
          }
        | {
            title: string;
            subtitle: string;
            background_image: string | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'lnk2_22';
          }
        | {
            title: string;
            subtitle: string;
            features: {
              title: string;
              description: string;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'features11_10';
          }
        | {
            title: string;
            subtitle: string;
            features: {
              title: string;
              description: string;
              feature_image_light: string | Media;
              feature_image_dark: string | Media;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'features2_21';
          }
        | {
            features: {
              s_no: number;
              title: string;
              description: string;
              id?: string | null;
            }[];
            background_image: string | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'ct04_16';
          }
        | {
            features: {
              title: string;
              description: string;
              id?: string | null;
            }[];
            background_image: string | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'ct02_45';
          }
        | {
            title: string;
            subtitle: string;
            reviews: {
              review: string;
              name: string;
              designation: string;
              reviewer_image: string | Media;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'reviews2_8';
          }
        | {
            title: string;
            description: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'banner7_7';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}